package com.arthurspirke.cvcreator.entity.enums;

public enum EntityType {
   CERTIFICATE, EDUCATION, EMPLOYMENT_HISTORY, LINKS_TO_FILES, PERSON, PHONE_NUMBERS, PERSONAL_LINKS, PROJECT, SKILLS, ADDRESS, PERSONAL_INFO, PERSONAL_TEMPLATES
}
